<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>API Documentation - Kotcoin Payment</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="min-h-screen bg-gradient-to-tr from-blue-500 via-green-500 to-purple-500 flex items-center justify-center">
    <div class="bg-white bg-opacity-95 p-8 rounded-2xl shadow-2xl border-t-4 border-blue-400 max-w-2xl w-full">
        <h2 class="text-3xl font-extrabold text-gray-800 mb-6 text-center">Kotcoin Payment API Documentation</h2>
        <h3 class="text-xl font-bold text-blue-700 mb-2">1. Generate Your API Key</h3>
        <p class="mb-4">Log in and visit <code class="bg-gray-100 px-2 py-1 rounded">api_key.php</code> to generate and view your API key. Keep it secret!</p>
        <h3 class="text-xl font-bold text-blue-700 mb-2">2. Make a Payment</h3>
        <p class="mb-2">Send a <b>POST</b> request to:</p>
        <pre class="bg-gray-100 p-2 rounded mb-2">/api/pay.php</pre>
        <p class="mb-2">With the following parameters:</p>
        <ul class="list-disc ml-8 mb-4">
            <li><b>api_key</b> (string, required): Your API key</li>
            <li><b>receiver_code</b> (string, required): The code generated by the receiver</li>
            <li><b>amount</b> (float, required): Amount in Kotcoin to send</li>
        </ul>
        <h4 class="font-semibold mb-1">Example Request (cURL):</h4>
        <pre class="bg-gray-100 p-2 rounded mb-4">curl -X POST \
  -d "api_key=YOUR_API_KEY" \
  -d "receiver_code=123456" \
  -d "amount=10" \
  http://yourdomain.com/api/pay.php</pre>
        <h4 class="font-semibold mb-1">Example Success Response:</h4>
        <pre class="bg-green-100 p-2 rounded mb-4">{
  "success": true,
  "transaction_code": "ABCDE",
  "message": "Money sent successfully!"
}</pre>
        <h4 class="font-semibold mb-1">Example Error Response:</h4>
        <pre class="bg-red-100 p-2 rounded mb-4">{
  "error": "Invalid API key."
}</pre>
        <h3 class="text-xl font-bold text-blue-700 mb-2 mt-6">3. Notes</h3>
        <ul class="list-disc ml-8 mb-4">
            <li>All payments are in Kotcoin (1 Kotcoin = 2.50 Rupees).</li>
            <li>Receiver code must be active and not expired.</li>
            <li>Check your balance before making a payment.</li>
            <li>Use the transaction code from the response to check the receipt.</li>
        </ul>
        <h3 class="text-xl font-bold text-blue-700 mb-2 mt-6">4. Example: JavaScript (fetch)</h3>
        <pre class="bg-gray-100 p-2 rounded mb-4">fetch('/api/pay.php', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: new URLSearchParams({
    api_key: '74c5fc4439effbea612fdba086e16d3ecfcd32125bd36742787da7063be249c9',
    receiver_code: 'RECEIVER_CODE',
    amount: 20
  })
})
.then(res => res.json())
.then(data => console.log(data));
</pre>
        <h3 class="text-xl font-bold text-blue-700 mb-2 mt-6">5. Try It: Direct Link</h3>
        <form id="apiTestForm" class="mb-4 flex flex-col md:flex-row gap-2 items-center">
            <input type="text" id="receiverCodeInput" placeholder="Enter Receiver Code" class="border border-gray-300 px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 transition" required />
            <button type="button" id="apiTestBtn" class="bg-gradient-to-r from-blue-500 to-green-500 text-white px-4 py-2 rounded-lg font-semibold shadow-lg hover:from-blue-600 hover:to-green-600 transition">Send 20 Kotcoin</button>
        </form>
        <div id="apiTestResult" class="mb-4"></div>
        <script>
        document.getElementById('apiTestBtn').onclick = function() {
            var code = document.getElementById('receiverCodeInput').value.trim();
            if (!code) {
                alert('Please enter a receiver code.');
                return;
            }
            var resultDiv = document.getElementById('apiTestResult');
            resultDiv.innerHTML = 'Processing...';
            fetch('/api/pay.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: new URLSearchParams({
                    api_key: '74c5fc4439effbea612fdba086e16d3ecfcd32125bd36742787da7063be249c9',
                    receiver_code: code,
                    amount: 20
                })
            })
            .then(res => res.json())
            .then(data => {
                resultDiv.innerHTML = '<pre class="bg-gray-100 p-2 rounded">' + JSON.stringify(data, null, 2) + '</pre>';
            })
            .catch(err => {
                resultDiv.innerHTML = '<span class="text-red-600">Error: ' + err + '</span>';
            });
        };
        </script>
        <div class="text-center mt-4">
            <a href="dashboard.php" class="text-blue-600 font-semibold hover:underline">← Back to Dashboard</a>
        </div>
    </div>
</body>
</html> 